[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "data-extraction"
version = "0.1.0"
description = "Invoice Data Extraction API"
requires-python = ">=3.8"

[project.scripts]
# Vercel looks for an `app` script that points to the ASGI app object.
app = "api:app"
