[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "data-extraction"
version = "0.1.0"
description = "Invoice Data Extraction API"
authors = ["you <taklikarbharat8@gmail.com>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "*"

[tool.poetry.scripts]
app = "api:app"
